prometheus-pve/prometheus-pve-exporter

- src/pve_exporter/cli.py
- src/pve_exporter/config.py
- src/pve_exporter/http.py
> Refuse to start with invalid configuration

- src/pve_exporter/collector.py
> Fix failure when some node is unavailable

- CHANGELOG.rst
- README.rst
- setup.py
> Move repo to prometheus-pve github org

- README.rst
> Fix travis links for changed org

- .travis.yml
- Dockerfile
- README.rst
> Add dockerfile and autopublish to dockerhub

- src/pve_exporter/collector.py
> Remove ip and local label from pve_node_info gauge

- README.rst
- src/pve_exporter/cli.py
- src/pve_exporter/collector.py
- src/pve_exporter/http.py
> Add command line flags to enable/disable individual collectors

- src/pve_exporter/collector.py
Co-authored-by: Leah Oswald <m...@l...>
> Do not fail scrape if some node is unresponsive

- README.rst
> docs: metrics sample; token id

- pylintrc
- src/pve_exporter/collector.py
- src/pve_exporter/config.py
- src/pve_exporter/http.py
After base system change in the ci image, `pylint` reported more issues in the code base. Let's just fix them.
> Fix ci (pylint issues)

- .github/workflows/container-image.yml
We currently only build container images for amd64, let's also build for arm64
> ci: add arm64 image build

- .github/workflows/ci.yml
> Remove references to develop branch

- Dockerfile
> Run with a dedicated user in container by default

- .github/workflows/pypi.yml
> Implement pypi trusted publishing workflow

- Dockerfile
- README.rst
- src/pve_exporter/cli.py
> Use flags instead of positional arguments for config file and listen address

- .github/workflows/pypi.yml
> Revert to deprecated way of building packages

- Dockerfile
> Simplify container build spec

- README.rst
- src/pve_exporter/collector/cluster.py
> Fix metrics docs

- README.rst
- src/pve_exporter/collector/cluster.py
> Add pve_ha_state and pve_lock_state metrics

- README.rst
- src/pve_exporter/collector/cluster.py
* Add plugintype and content labels to pve_storage_info
* Add pve_up metric for storage
Fixes #152
> Extend storage info

- src/pve_exporter/collector/cluster.py
The `content` label of the `pve_storage_info` metric is a multi-value label, encoded in a comma-separated string. The returned from the Proxmox library is randomly sorted. This means that on every single scrape, the label returns a slightly different value.
This causes a pretty major performance problem. Different label values results in different series, which causes a different time series to be returned for the metric every single time the exporter is scraped. It also causes cardinality to go from `storage_instance_count` (linear) to `storage_instance_count * !content_type_count` (factorial). This gets worse with the number of node scraped, the number of storage entries, and the number of different content types served by each storage entry.
Here's an example of how many time series …
> Fix storage content label causing churn rate + cardinality explosion
